name: Clientlib
on: [ push, pull_request ]
jobs:
  test:
    name: Clientlib tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: run tests
      run: |
        cd clientlib
        npm cache clean --force
        npm install
        npm run test
